routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{ContactController, HelpController, ProductController, HomeController, PermissionController, ProfileController, RoleController, SettingController, UserController, PreviewThemeProductController};
use App\Http\Controllers\Integrate\GoogleContactController;
use App\Http\Controllers\Integrate\KirimEmailController;
use App\Http\Controllers\Integrate\WhatsappController;
use App\Http\Controllers\Whatsapp\BroadcastController;

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');

    Route::resource('/products', ProductController::class)->except('show');
    Route::prefix('products')->name('products.')->group(function () {
        Route::delete('/', [ProductController::class, 'bulk_destroy'])->name('bulk_destroy');

        // Product's images routes
        Route::prefix('/{id}/images')->group(function () {
            Route::get('/create', [ProductController::class, 'create_images'])->name('create_images');
            Route::post('/create', [ProductController::class, 'store_images']);
            Route::get('/edit', [ProductController::class, 'edit_images'])->name('edit_images');
            Route::put('/edit', [ProductController::class, 'update_images']);
        });

        // Product's pricing routes
        Route::prefix('/{id}/pricings')->group(function () {
            Route::get('/create', [ProductController::class, 'create_pricings'])->name('create_pricings');
            Route::post('/create', [ProductController::class, 'store_pricings']);
            Route::get('/edit', [ProductController::class, 'edit_pricings'])->name('edit_pricings');
            Route::put('/edit', [ProductController::class, 'update_pricings']);
        });

        // Product's bump routes
        Route::prefix('/{id}/bumps')->group(function () {
            Route::get('/create', [ProductController::class, 'create_bumps'])->name('create_bumps');
            Route::post('/create', [ProductController::class, 'store_bumps']);
            Route::get('/edit', [ProductController::class, 'edit_bumps'])->name('edit_bumps');
            Route::put('/edit', [ProductController::class, 'update_bumps']);
        });

        // Product's shipping routes
        Route::prefix('/{id}/shippings')->group(function () {
            Route::get('/create', [ProductController::class, 'create_shippings'])->name('create_shippings');
            Route::post('/create', [ProductController::class, 'store_shippings']);
            Route::get('/edit', [ProductController::class, 'edit_shippings'])->name('edit_shippings');
            Route::put('/edit', [ProductController::class, 'update_shippings']);
        });

        // Product's payment routes
        Route::prefix('/{id}/payments')->group(function () {
            Route::get('/create', [ProductController::class, 'create_payments'])->name('create_payments');
            Route::post('/create', [ProductController::class, 'store_payments']);
            Route::get('/edit', [ProductController::class, 'edit_payments'])->name('edit_payments');
            Route::put('/edit', [ProductController::class, 'update_payments']);
        });

        // Product's unique code routes
        Route::prefix('/{id}/unique_codes')->group(function () {
            Route::get('/create', [ProductController::class, 'create_unique_code'])->name('create_unique_codes');
            Route::post('/create', [ProductController::class, 'store_unique_code']);
            Route::get('/edit', [ProductController::class, 'edit_unique_code'])->name('edit_unique_codes');
            Route::put('/edit', [ProductController::class, 'update_unique_code']);
        });

        // Product's checkout page routes
        Route::prefix('/{id}/checkout-page')->group(function () {
            Route::get('create', [ProductController::class, 'create_checkout_page'])->name('create_checkout_page');
        });
    });

    Route::prefix('whatsapp')->group(function () {
        Route::delete('/broadcasts', [BroadcastController::class, 'bulk_destroy'])->name('broadcasts.bulk_destroy');
        Route::get('/broadcasts/history', [BroadcastController::class, 'list'])->name('broadcasts.history');
        Route::get('/broadcast/schedule', [BroadcastController::class, 'schedule'])->name('broadcasts.schedule');
        Route::delete('/broadcast/schedule', [BroadcastController::class, 'bulk_destroy_schedule']);
        Route::resource('/broadcasts', BroadcastController::class)->except('edit', 'update');
    });

    Route::prefix('integrate')->group(function () {
        Route::delete('/whatsapp', [WhatsappController::class, 'bulk_destroy'])->name('whatsapp.bulk_destroy');
        Route::resource('/whatsapp', WhatsappController::class)->except('show');

        Route::delete('/kirim-email', [KirimEmailController::class, 'bulk_destroy'])->name('kirim-email.bulk_destroy');
        Route::resource('/kirim-email', KirimEmailController::class)->except('show');

        Route::get('/google-contact/auth', function () {
            return view('pages.integrate.googlecontact.authCode');
        });
        Route::post('/google-contact/auth', [GoogleContactController::class, 'auth'])->name('google-contact.auth');
        Route::post('/google-contact/fetch-code', [GoogleContactController::class, 'fetchCode'])->name('google-contact.fetchCode');
        Route::delete('/google-contact', [GoogleContactController::class, 'bulk_destroy'])->name('google-contact.bulk_destroy');
        Route::resource('/google-contact', GoogleContactController::class)->except('show');
    });

    Route::delete('/contacts', [ContactController::class, 'bulk_destroy'])->name('contacts.bulk_destroy');
    Route::resource('/contacts', ContactController::class)->except('show');

    Route::delete('/users', [UserController::class, 'bulk_destroy'])->name('users.bulk_destroy');
    Route::resource('/users', UserController::class)->except('show');

    Route::delete('/roles', [RoleController::class, 'bulk_destroy'])->name('roles.bulk_destroy');
    Route::resource('/roles', RoleController::class)->except('show');

    Route::resource('/permissions', PermissionController::class)->only('index');

    Route::resource('/settings', SettingController::class)->only('index', 'udpate');

    Route::get('help', [HelpController::class, 'index'])->name('help.index');

    Route::get('preview-product', [PreviewThemeProductController::class, 'index']);
});

app/Models/GoogleContact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GoogleContact extends Model
{
    use HasFactory;
    
    public $timestamps = false;
    
    protected $table = 'integrate_google_contact';

    protected $fillable = [
        'application_name' , 'client_id', 'client_secret', 'redirect_uri', 'access_token', 'expires_in', 'refresh_token', 'scope', 'token_type', 'created'
    ];

}

app/Http/Controllers/Integrate/GoogleContactController.php
<?php

namespace App\Http\Controllers\Integrate;

use App\Helpers\GContact;
use App\Http\Controllers\Controller;
use App\Http\Requests\GoogleContactRequest;
use App\Models\GoogleContact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

class GoogleContactController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:google-contact-read|google-contact-create|google-contact-update|google-contact-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:google-contact-create', ['only' => ['create', 'store', 'auth']]);
        $this->middleware('permission:google-contact-update', ['only' => ['edit', 'update']]);
        $this->middleware('permission:google-contact-delete', ['only' => ['destroy', 'bulk_destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $index = 0;
        $gContacts = [];
        $all = GoogleContact::all();
        foreach ($all as $item) {
            $gContacts[$index] = $item;
            $gContacts[$index]["encryptid"] = encrypt($item->id);
            $index++;
        }

        if (request()->get('type') == "json") {
            return response()->json($gContacts);
        }

        return view('pages.integrate.googlecontact.index', compact('gContacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.integrate.googlecontact.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GoogleContactRequest $request)
    {
        GoogleContact::create($request->all());

        return redirect()->back()->with('create-success', true);
    }

    public function auth(Request $request)
    {
        $gContact = new GContact();

        $validator = Validator::make($request->all(), [
            'application_name' => 'required|string',
            'client_id' => 'required|string',
            'client_secret' => 'required|string',
            'redirect_uri' => 'required|url'
        ]);

        if($validator->fails()) {
            return response()->json([
                'status' => 'error',
                'type' => 'validation',
                'messages' => $validator->errors()
            ], Response::HTTP_BAD_REQUEST);
        }

        $gContact = new GContact;
        return $gContact->generateAuthUri($request->all());
    }

    public function fetchCode(Request $request)
    {
        $gContact = new GContact;
        $fetch = $gContact->fetchAccToken($request->client, $request->accessCode);

        if($fetch['status'] == 'error') {
            return response()->json($fetch, Response::HTTP_UNPROCESSABLE_ENTITY);
        }

        return response()->json($fetch, Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function bulk_destroy(Request $request)
    {
        $gContacts = json_decode($request->gcontacts);
        
        foreach($gContacts as $gContact) {
            GoogleContact::destroy($gContact->id);
        }

        return redirect()->back()->with('bulk-destroy-success', 1);
    }
}

app/Http/Controllers/Integrate/KirimEmailController.php
<?php

namespace App\Http\Controllers\Integrate;

use App\Http\Controllers\Controller;
use App\Models\KirimEmail;
use Illuminate\Http\Request;

class KirimEmailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kirimemail = [];

        $index = 0;
        $data = KirimEmail::all();
        foreach ($data as $item) {
            $kirimemail[$index] = $item;
            $kirimemail[$index]["encryptid"] = encrypt($item->id);
        }

        if (request()->get('type') == "json") {
            return response()->json($kirimemail);
        }

        return view('pages.integrate.kirimemail.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("pages.integrate.kirimemail.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'username' => 'required|unique:integrate_kirim_email',
            'token' => 'required'
        ]);

        $kirimemail = KirimEmail::create($request->all());
        return redirect()->route('kirim-email.edit', encrypt($kirimemail->id))
            ->with('store-success', 'Action create integrate kirim.email successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kirimemail = KirimEmail::find(decrypt($id));
        return view("pages.integrate.kirimemail.edit", compact('kirimemail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'username' => 'required|unique:integrate_kirim_email,username,' . decrypt($id),
            'token' => 'required'
        ]);

        $kirimemail = KirimEmail::find(decrypt($id));
        $kirimemail->fill($request->all());
        $kirimemail->save();

        return redirect()->back()
            ->with('store-success', 'Action create integrate kirim.email successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kirimemail = KirimEmail::find(decrypt($id));
        $kirimemail->delete();

        return redirect()->route('kirim-email.index')
            ->with('destroy-success', 'Action destroy integrate kirim.email is successfully');
    }

    /**
     * Remove the resource selected from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function bulk_destroy()
    {
        $kirimemails = json_decode(request()->kirimemails);
        foreach ($kirimemails as $kirimemail) {
            $data = KirimEmail::find($kirimemail->id);
            $data->delete();
        }
        return redirect()->back()
            ->with('bulk-destroy-success', 'Action bulk destroy integrate kirim.email is successfully');
    }
}

resources/views/pages/integrate/googlecontact/authCode.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Auth Code</title>
</head>
<body>
    <div id="access-code" data-code="{{ request()->code }}"></div>
    <script>
        const authCode = window.opener.document.getElementById('auth-code');
        const accessCode = document.getElementById('access-code');

        authCode.setAttribute('data-code', accessCode.dataset.code);
        window.close();
    </script>
</body>
</html>

resources/views/pages/integrate/googlecontact/create.blade.php
@extends('layouts.main')

@section('header')
<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
    <h3 class="content-header-title mb-0 d-inline-block">
        <i class="la la-google"></i>
        {{ __('pages.googlecontacts') }}
    </h3>
    <div class="row breadcrumbs-top d-inline-block">
        <div class="breadcrumb-wrapper col-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('breadcrumb.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('breadcrumb.googlecontacts') }}</li>
            </ol>
        </div>
    </div>
</div>
@endsection

@section('content')
<div id="auth-code" data-code=""></div>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4>Create Google Contact Integration</h4>
            </div>
            <div class="card-body">
                <form method="post" id="gcontact-form">
                    @csrf
                    @include('pages.integrate.googlecontact.components.form')
                    <input type="hidden" name="access_token" id="access_token">
                    <input type="hidden" name="created" id="created">
                    <input type="hidden" name="expires_in" id="expires_in">
                    <input type="hidden" name="refresh_token" id="refresh_token">
                    <input type="hidden" name="scope" id="scope">
                    <input type="hidden" name="token_type" id="token_type">
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('stylesheet')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/tables/datatable/select.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/extensions/sweetalert2.min.css') }}">
@endsection

@section('javascript')
<script src="{{ asset('assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/tables/datatable/dataTables.select.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
<script>
    $.oauthpopup = function(options) {
        options.windowName = options.windowName ||  'ConnectWithOAuth';
        options.windowOptions = options.windowOptions || 'location=0,status=0,width=800,height=400';
        options.callback = options.callback || function(){ window.location.reload(); };
        var that = this;
        that._oauthWindow = window.open(options.path, options.windowName, options.windowOptions);
        that._oauthInterval = window.setInterval(function(){
            if (that._oauthWindow.closed) {
                window.clearInterval(that._oauthInterval);
                options.callback();
            }
        }, 1000);
    };

    function fetchAccTokenWithAuthCode(code) {
        if(code.length < 1) {
            return Swal.fire({
                icon: 'error',
                title: 'Error',
                text: 'Cannot get auth code',
                showConfirmButton: false,
                buttonsStyling: false,
                timer: 2000,
                timerProgressBar: true,
            });
        }

        const authData = {};
        $('#gcontact-form').serializeArray().map(function(data) {
            authData[data.name] = data.value;
        });

        $.ajax({
            url: '{{ route('google-contact.fetchCode') }}',
            method: 'POST',
            dataType: 'json',
            data: {
                _token: authData._token,
                client: authData,
                accessCode: code
            },
            success: function(res) {
                if(res.status == 'success') {
                    const form = $('#gcontact-form');

                    $.each(res.data, function(name, value) {
                        $(`#${name}`).val(value);
                    });

                    $('#btn-save-gauth').text('Save');
                    form.attr('action', '{{ route('google-contact.store') }}');
                    form.off('submit');
                    form.submit();
                }
            },
            error: function(res, status, err) {
                if(res.status == 422) {
                    const error = res.responseJSON;

                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: error.message,
                        showConfirmButton: false,
                        buttonsStyling: false,
                        timer: 2000,
                        timerProgressBar: true,
                    });
                }
            }
        });
    }

    $('#gcontact-form').submit(function(e) {
        e.preventDefault();
        let form = $(this);

        $('.form-control').removeClass('is-invalid');
        $('.invalid-feedback').html('');

        $.ajax({
            url: '{{ route('google-contact.auth') }}',
            method: 'post',
            data: form.serialize(),
            success: function(e) {
                $.oauthpopup({
                    path: e,
                    callback: function() {
                        const authCode = document.getElementById('auth-code');
                        fetchAccTokenWithAuthCode(authCode.dataset.code);
                    }
                });
            },
            error: function(res, status, err) {
                if(res.status == 400) {
                    error = res.responseJSON;

                    $.each(error.messages, function(name, msg) {
                        $(`#${name}`).addClass('is-invalid');
                        $(`.invalid-feedback.invalid-${name}`).html(msg);
                    });
                    
                }
            }
        });
    });
</script>

@if(Session::has('create-success'))
<script type="text/javascript">
    $(document).ready(function() {
        Swal.fire({
            icon: 'success',
            title: 'Success',
            text: 'GContact integration saved successfully.',
            showConfirmButton: false,
            buttonsStyling: false,
            timer: 2000,
            timerProgressBar: true,
        });
    });
</script>
@endif

@endsection

resources/views/pages/integrate/googlecontact/index.blade.php
@extends('layouts.main')

@section('header')
<div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
    <h3 class="content-header-title mb-0 d-inline-block">
        <i class="la la-google"></i>
        {{ __('pages.googlecontacts') }}
    </h3>
    <div class="row breadcrumbs-top d-inline-block">
        <div class="breadcrumb-wrapper col-12">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('breadcrumb.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('breadcrumb.googlecontacts') }}</li>
            </ol>
        </div>
    </div>
</div>
<div class="content-header-right text-right col-md-6 col-12">
    @can('google-contact-delete')
    <button type="button" class="btn btn-danger text-white btn-bulk-destroy" disabled>
        <i class="la la-trash"></i> {{ __('button.bulk_destroy') }}
    </button>
    @endcan

    @can('google-contact-create')
    <a href="{{ route('google-contact.create') }}" class="btn btn-primary text-white">
        <i class="la la-plus-circle"></i> {{ __('button.create') }}
    </a>
    @endcan
</div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-body">
            <table class="table datatable" width="100%"></table>
        </div>
    </div>
</div>

<form id="bulk-destroy" action="{{ route('google-contact.bulk_destroy') }}" method="post" class="d-none">
    @csrf
    @method('delete')
    <input type="text" name="gcontacts">
</form>
@endsection

@section('stylesheet')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/tables/datatable/select.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/css/extensions/sweetalert2.min.css') }}">
@endsection

@section('javascript')
<script src="{{ asset('assets/vendors/js/tables/datatable/datatables.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/tables/datatable/dataTables.select.min.js') }}"></script>
<script src="{{ asset('assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>

<script type="text/javascript">
    var selected = [];

    $(document).ready(function() {
        $('.datatable').DataTable({
            width: '100%',
            processing: true,
            select: {
                style: 'os',
                selector: 'td:first-child .select-checkbox'
            },
            ajax: {
                url: '{{ route('google-contact.index') }}?type=json',
                dataSrc: (data) => {
                    return data;
                }
            },
            order: [
                [1, 'asc']
            ],
            columns: [{
                defaultContent: '',
                title: '',
                orderable: false,
                className: 'select-checkbox pr-1 pl-2',
                width: '10px'
            }, {
                data: 'application_name',
                title: 'Application Name',
                orderable: true,
            }, {
                data: 'client_id',
                title: 'Client ID',
                orderable: false
            }],
            rowCallback: (row, data, index) => {
                @if(Auth::user()->can('contact-delete'))
                    $('td:first-child', row).on('click', function() {
                        if (!$(row).hasClass('selected')) {
                            $(row).addClass('selected');
                            selected.push(data);
                        } else {
                            $(row).removeClass('selected');
                            selected.splice(selected.indexOf(data.id), 1);
                        }

                        if (selected.length > 0) {
                            $('.btn-bulk-destroy').removeAttr('disabled');
                        } else {
                            $('.btn-bulk-destroy').attr('disabled', 'disabled');
                        }
                    });
                @endif
            }
        });
    });

    $('.btn-bulk-destroy').on('click', () => {
        Swal.fire({
            title: 'Are you sure?',
            text: "Are you going to bulk destroy selected data?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonClass: 'btn btn-danger',
            cancelButtonClass: 'btn btn-secondary',
            confirmButtonText: 'Yes, destroy it!',
        }).then((result) => {
            $('#bulk-destroy input[name="gcontacts"]').val(JSON.stringify(selected));
            $('#bulk-destroy').submit();
        });
    });
</script>

@if(Session::has('destroy-success'))
<script type="text/javascript">
    $(document).ready(function() {
        Swal.fire({
            icon: 'success',
            title: 'Success',
            text: 'Action destroy contact is successfully.',
            showConfirmButton: false,
            buttonsStyling: false,
            timer: 2000,
            timerProgressBar: true,
        });
    });
</script>
@endif

@if(Session::has('bulk-destroy-success'))
<script type="text/javascript">
    $(document).ready(function() {
        Swal.fire({
            icon: 'success',
            title: 'Success',
            text: 'Action bulk destroy GContact is successfully.',
            showConfirmButton: false,
            buttonsStyling: false,
            timer: 2000,
            timerProgressBar: true,
        });
    });
</script>
@endif
@endsection